### ISSUE TITLE
Running `yup make` returns index out of range

### ISSUE THREAD

**Issue by ericm** [ericm/yup#14]
```
[seqularise@desktop ~]$ yup make
==> Searching and sorting your query...
panic: runtime error: index out of range

goroutine 20 [running]:
github.com/ericm/yup/search.Pacman(0x7ffc745429ff, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/seqularise/.cache/yay/yup/src/yup/search/search.go:184 +0x1372
github.com/ericm/yup/cmd.(*Arguments).getActions.func2(0x9b4f60, 0xc00007ec50, 0xc0000741e0)
        /home/seqularise/.cache/yay/yup/src/yup/cmd/cmd.go:184 +0x54
created by github.com/ericm/yup/cmd.(*Arguments).getActions
        /home/seqularise/.cache/yay/yup/src/yup/cmd/cmd.go:182 +0x7c9
[seqularise@desktop ~]$

**Comment by Seqularise** [comment]
yup -Syu is working, yup -Ss gives a little different output, it begins to show items but proceeds to error anyway

**Comment by ericm** [comment]
It's an issue in `package search` I'd say
